- src/layer.js
Hey there, first thanks for this project.
I was playing around the mapbox component and I realised that currently the `feature` method for build a `feature object` itself, inside the Layer component doesn't allow put the `properties` attribute, so there would be nice to have this custom functionality. So, for instance the `Feature` component will receive that new attribute in props. (ref to http://plnkr.co/edit/W7pfGHVBzJj8U3AmPyzf?p=preview)
If there is another way to do this please don't doubt on tell me. Cheers
```
<Layer
id="markers"
type="symbol"
layout={ {
"icon-image": "{marker-symbol}-15",
"text-field": "{title}",
"text-font": ["Open Sans Semibold", "Arial Unicode MS Bold"],
"text-offset": [0, 0.6],
"text-anchor": "top"
} }>
{
stations
.map( ( station, index ) => (
<Feature
key={ …
```
> Allowing properties attribute for feature

- src/map.js
Allows user to pass in a 'pitch' properly so that the map can be tilted on initial load. More info in [MapBox Javascript GL API docs](https://www.mapbox.com/mapbox-gl-js/api/#Map).
Example usage:
```
state = {
center: [-0.109970527, 51.52916347],
pitch: [60],  // Angle in degress to tilt map. Max === 60.
zoom: [11],
skip: 0,
stations: new Map(),
popupShowLabel: true
};
render() {
return (
<div className="map-container">
<ReactMapboxGl
style={style}
center={this.state.center}
zoom={this.state.zoom}
pitch={this.state.pitch}
minZoom={8}
maxZoom={15}
maxBounds={maxBounds}
accessToken={accessToken}
onDrag={this._onDrag}
onMoveEnd={this._setMove.bind(this, true)}
onMove={this._setMove.bind(this, false)}
containerStyle={containerStyle}
/>
</div>
)
}
```
> Removes duplicate state object and adds support for pitch property.

- docs/API.md
- src/map.js
Hi!
In a personal project, I needed to position the mapbox attribution in the top-right corner, instead of the bottom-right. So I added it as a prop. 
No worries if you're not interested in accepting this PR, but I thought I'd open it in case others could benefit.
The implementation was pretty straightforward. The only bit I'm unsure of is whether it's best to have an `attributionPosition` prop (as I've done), or to mirror the official API more closely with an `attributionControl` prop that takes an object.
I've opted for simplicity over accuracy, but let me know if it should be flipped :)
> Add support for AttributionControl position

- src/map.js
The comparison of this.props and nextProps uses reference comparison now. For comparing the current map camera options with the corresponding nextProps properties, primitive data types are compared.
> Feature/improve camera options comparison (with reference comparison)

- src/zoom-control.js
Fixes #76 in which the `ZoomControl` component wasn't respecting Mapbox's movingMethod and zooming was jumpy instead of animated by default.
> Animated zoom

- docs/API.md
API docs was missing the `dragRotate` in the property list for `ReactMapboxGl` component.
> ReactMapboxGl was missing dragRotate property

- src/marker.js
just noticed this change as a result of https://github.com/alex3165/react-mapbox-gl/commit/4f7a4ddac7a34f38fc78e25ba5c4d2cdbd3fdbe1 and I think you meant to keep the name `Marker`. 
thanks!
> fix name of marker class

- README.md
- docs/API.md
- src/index.js
- src/layer.js
- src/source.js
This PR makes it so that the following is valid:
```
<Source id="example_id" sourceOptions={RASTER_SOURCE_OPTIONS} />
<Layer type="raster" id="example_id" sourceId="example_id" />`
```
Will add documentation before merging but wanted to put this up for public scrutiny.
> raster layer enabled and source component

- src/source.js
Right now if you create a `<Source>` component with GeoJSON data, the data can't be updated after the component is mounted.
This would allow you to update the GeoJSON data e.g. `<Source id="source-id" sourceOptions={{type: 'geojson', data: geojsonData}}>` and have mapbox-gl re-render when the data changes.
> Source component should respond to sourceOptions.data updates

- src/__tests__/layer.test.tsx
- src/layer.ts
Previously, if you had a Layer that had Features as children,
and then the props changed such that the Layer no longer had
children, <source>.setData would not be called to remove the
Features from the source.
To fix this, I've changed Layer so that it will always call
setData when rendered. This should be fine because Layer#render
will only be called if the component should update.
I've added tests as well.
> call setData when children disappear

- example/src/all-shapes.js
In all-shapes example errors were thrown by the example component being unmounted and having the timer or the interval still updating its state.
This PR adds a timer handle, an interval handle and a flag, together with a componentWillUnmount method that will clear both timer and interval, avoiding the exception to be thrown.
> Fix all-shapes example 

- .gitignore
- example/package.json
- package.json
- src/__tests__/map.test.tsx
- src/__tests__/overlays.test.ts
- src/cluster.tsx
- src/geojson-layer.ts
- src/map.tsx
- src/source.ts
- src/util/overlays.ts
- src/util/types.ts
- tsconfig.json
This PR will:  
* Update *all dependencies* (including devDependencies, peerDependencies, example) to their latest versions (I used `npm outdated`).
* add .vscode to .gitignore (local workspace settings, for my mental sanity 😌  )
* Also fix a couple of tslint errors (extra semicolons etc) which were not found by the previous version of tslint.
* Use latest tsc which requires expliciting "libs" in the tsconfig.json
* Finally, fix import of `'mapbox-gl/dist/mapbox-gl'` to just `'mapbox-gl'`. This will works just the same way, because mapbox main module is 'mapbox-gl/dist/mapbox-gl' (see their package.json). **But this will allow people to define alias** in their webpack config files in their projects, e.g. for using mapbox-gl-dev or for compiling it from source. This makes the current …
> Deps update

- docs/API.md
- package.json
- src/__tests__/layer.test.tsx
- src/__tests__/source.test.tsx
- src/source.ts
When adding the Source, data don't get loaded.
This fix this behavior by adding a one-time listener to [map:load](https://www.mapbox.com/mapbox-gl-js/api/#map.event:load) and setting source data.
This guarantees data being available after the load event has occurred. 
This PR also adds a `onSourceLoaded` which is similar to `onSourceAdded` and gets called after the map:load event.
I also updated the API.md docs
> Fix bug in source data not being loaded by geojson source

- docs/API.md
- src/map.tsx
- src/util/mapbox-type.d.ts
Added map property `renderWorldCopies` according to the Mapbox GL API (https://www.mapbox.com/mapbox-gl-js/api/).
My editor also killed some trailing whitespace automatically in the files I touched. Hope this is ok.
> Exposed renderWorldCopies Map option to properties.

- src/zoom-control.tsx
add  type="button" to prevent default behaviour (form submission inside form)
> Zoom control buttons should not cause form submission

- src/__tests__/diff.test.ts
- src/util/diff.ts
The current diff only returns keys that are in both objects, so anything added or removed from paint/layout doesn't get updated on the map.
> Include new and removed keys in diff results

- README.md
doesn't seem needed now that it is set on the Factory. Also invalid JSX.
> removing empty accessToken=

- src/map.tsx
This should solve #136.
A reference to the map object needs to be available at all times, or it won't receive the updated `fitBounds` (or any other property for that matter).
> Fix #136 fitBounds burst issue

- docs/API.md
- example/src/demos/htmlCluster.tsx
- src/__tests__/cluster.test.tsx
- src/cluster.tsx
- src/layer.ts
- src/popup.tsx
- src/projected-layer.tsx
- src/util/overlays.ts
Feature asked in #208 
It's working, but something must be changed in the cluster API to transmit original feature properly.
Until today, converting `Marker` props to feature was good enough, since we didn't need to access properties of the original feature.
Right now the only thing `getLeaves` can return is `Marker` component, which doesn't contain original feature data.
So in order to show what's inside the `Marker` we have to do this (two children here to skip the div element): `{leaf.props.children.props.children}`).
We could store the feature inside `Marker` and get it like that: `{leaf.props['data-feature']}`.
But it doesn't feel right...
> WIP: feat(cluster): add getLeaves argument to factory

- src/cluster.tsx
Pass through the arguments to supercluster so the pagination actually works [as documented](https://github.com/alex3165/react-mapbox-gl/blob/ac71beba10b644fcfb8b6345ab13008e956dd554/docs/API.md#properties-9)
> fix(cluster): actually use the arguemnts provided to getLeaves

- docs/API.md
- src/index.ts
- src/map.tsx
CSS injection can now be deactivated by passing `injectCss: false` to the Map factory.
To prevent a breaking change, the legacy way of injecting CSS is still on by default and has to be deactivated via `window.MAPBOX_SKIP_CSS_INJECTION = true` before importing the package.
For the next release with breaking changes, the block in `index.ts` can simply be removed.
> Move CSS injection into Map factory; FIXES #397

- package-lock.json
- src/source.ts
It looks like #453 wasn't quite complete. I found that sometimes on a slow network connection the source will be there but some properties like `bounds` don't exist yet. Fortunately there is a function `isSourceLoaded` to check for other things like outstanding network requests.
> onSourceLoaded sometimes firing too soon

- src/map.tsx
This allows `padding` in `FitBoundsOptions` to be defined as `{ top, bottom, left, right } `.
https://www.mapbox.com/mapbox-gl-js/api/#map#fitbounds
https://www.mapbox.com/mapbox-gl-js/api/#paddingoptions
> Add interface PaddingOptions for FitBoundsOptions

- src/scale-control.tsx
_canvas.width seems to be twice as large as the actual clientWidth. In result, the scale control was being rendered twice as large as it should be; you can easily verify this using the example project and comparing the results to google map distance measurement, for example.
My fix uses clientWidth instead of canvas width, making the control the correct width. This leaves the control quite small, so I also adjusted the MIN_WIDTH_SCALE.
> Scale control is twice as width as it should be

- src/source.ts
Addresses: https://github.com/alex3165/react-mapbox-gl/issues/501
This ensures that the map has the source before attempting to set the data. This is important because `componentWillReceiveProps` is fired before the style change handler. Since all the sources are removed after the style change, this throws an error.
> Checks to ensure that the source has been added to the map

- src/__tests__/zoom-control.test.tsx
- src/zoom-control.tsx
When minus is hovered, `this.state.hovered` equals `0`, so the state is not changed on `mouseout`. It works if you mouseout from the plus button, but not from minus.
> ZoomControl minus button stays hovered on mouseout

- package.json
- src/__tests__/cluster.test.tsx
- src/projected-layer.tsx
Fixes #217 
Could switch to `ReactDOM.createPortal` at some point if dropping support for React 15
> Allow scroll events on HTML Layers

- README.md
- docs/API.md
- example/src/demos/allShapes.tsx
- example/src/demos/geojsonLayer.tsx
- example/src/demos/heatmap.tsx
- example/src/demos/htmlCluster.tsx
- example/src/demos/htmlFeatures.tsx
- example/src/demos/londonCycle.tsx
- example/src/demos/raws/allShapes.raw
- example/src/demos/raws/geojsonLayer.raw
- example/src/demos/raws/heatmap.raw
- example/src/demos/raws/htmlCluster.raw
- example/src/demos/raws/htmlFeatures.raw
- example/src/demos/raws/londonCycle.raw
- example/src/demos/raws/switchStyle.raw
- example/src/demos/raws/threeDMap.raw
- example/src/demos/switchStyle.tsx
- example/src/demos/threeDMap.tsx
- example/src/home-code.ts
- src/__tests__/map.test.tsx
- src/map.tsx
Fixes #498
- **style** &rightarrow; **mapStyle**
- **style** has been renamed to **mapStyle** to avoid confusion with DOM styles.
- **containerStyle** &rightarrow; **style**
- **containerStyle** has been renamed to **style** to adhere to standard React convention.
- The **style** prop now controls the DOM styles for the container element.
> rename style to mapStyle, containerStyle to style

- README.md
webpackbin has been deprecated. The maintainer has shifted their efforts to Codesandbox.io.
https://github.com/cerebral/webpackbin
> webpackbin is deprecated, remove from README

- docs/API.md
- package-lock.json
- package.json
- src/cluster.tsx
- src/geojson-layer.ts
- src/layer-events-hoc.tsx
- src/layer.ts
- src/map.tsx
- src/source.ts
- src/util/types.ts
This drops the `classes` prop that's no longer supported by mapbox-gl. Other than that, no functional changes, only updates mapbox-gl and its types (0.48 isn't released for @types/mapbox-gl yet – pending PR – so can't implement those features here nicely).
> feat: update to mapbox-gl@0.48.0

- src/cluster.tsx
Remove event listeners from unmounted Cluster component in order to prevent warning logs in regard with attempt to 'setState' on unmounted Cluster component when 'zoom' or 'move' map events are triggered.
> Resolves #567; Remove event listeners from unmounted Cluster component

- docs/API.md
- src/__tests__/layer.test.tsx
- src/layer.ts
Adding mouse events to the `<Layer>` component as requested in #563 and #621
> Add <Layer> Mouse event handlers

- docs/API.md
- src/__tests__/image.test.tsx
- src/image.tsx
- src/index.ts
- src/jest/util.tsx
Adds an Image component as requested in #455 
The image will load to the map then it can be used as [`icon-image`](https://www.mapbox.com/mapbox-gl-js/style-spec#layout-symbol-icon-image)
Closes #455 
Closes #569
> Adding Image component

- src/layer.ts
Fixes image removal during layer unmount. It first unsubscribes from map style data change to prevent re-initialization and binds mapbox-gl map object to removeImage function.
> Fix layer unmount remove image

- src/map.tsx
Fixes #666 
I was running into this issues and was just overwriting the definition myself. I felt bad because others saw the same problem so I thought I'd try to be helpful and fix it. This library is great and I respect it a ton but I am new to contributing to it so if I can do anything to fix this issue in a better, or more sustainable way I'd be happy to help. Thanks.
> fix: Type mismatch in module augmentation for mapbox-gl

- src/map.tsx
This fix was original merged (via #619) into an early v4 branch which has been abandoned. Using `createPortal` fixes capturing move/scroll/zoom events on Marker & Cluster elements
Closes #217 (again)
Closes #562
> Fix Marker & Cluster mouse events

- src/map-events.tsx
This allows for things like the mapBox example here:
[Generate and add a missing icon to the map](https://docs.mapbox.com/mapbox-gl-js/example/add-image-missing-generated/)
For our purposes, that should allow us to have dynamic symbol images with presumably better performance than a large list of custom Marker components.
> Add the styleimagemissing event from mapbox

- docs/API.md
- example/src/demos/htmlCluster.tsx
- example/src/demos/raws/htmlCluster.raw
- src/map.tsx
This flag defaulting to `false` brings back the default behaviour from prior to v4.3.0.
Setting it to `true` renders projected layers such as Popup and Marker in a React portal, allowing events to pass through them.
In hindsight, v4.3.0 basically introduced a breaking change and I'm making this change to "undo" it. Both functionalities will be available, with the original one being the default for the lifetime of v4.
Fixes #725
> renderChildrenInPortal Map prop to pass mouse events through projected layers

- package-lock.json
- package.json
See issue #756 
While there are no _code_ related breaking changes from this upgrade, it does change the pricing model on Mapbox for anyone using this library. This change will be required as of November 20, 2019 either way.
See here for details: https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md
> Upgrade mapbox-gl from 0.54.0 to 1.1.1

- docs/API.md
- package-lock.json
- package.json
- src/map.tsx
add `antialias` property (by default: `false`)
added to mapbox-gl-js in [v0.54.0](https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.54.0)
> add antialias support

- example/src/demos/allShapes.tsx
- example/src/demos/londonCycle.tsx
- example/src/demos/raws/allShapes.raw
- example/src/demos/raws/londonCycle.raw
- example/src/demos/raws/switchStyle.raw
- example/src/demos/switchStyle.tsx
- example/src/root.tsx
- src/cluster.tsx
- src/geojson-layer.ts
- src/image.tsx
- src/layer-events-hoc.tsx
- src/layer.ts
- src/map.tsx
- src/projected-layer.tsx
- src/scale-control.tsx
- src/source.ts
After updating to React v16.9.0 the console is cluttered with warnings about the deprecated use of unsafe lifecycle methods (`componentWillMount`, `componentWillReceiveProps`, `componentWillUpdate`).
The old names will still work in upcoming 16.x and 17.x releases, but in order to let them stand out (and get rid of the console warnings) they have to be prefixed with `UNSAFE_`.
https://reactjs.org/blog/2019/08/08/react-v16.9.0.html#renaming-unsafe-lifecycle-methods
> Rename unsafe lifecycle methods.

- src/scale-control.tsx
The map scale value also changes when the map moves north-south not only when with the zoom level.
> fix: events that trigger scale recalculation

- README.md
- src/__tests__/map.test.tsx
- src/cluster.tsx
- src/map.tsx
Remove injectCss in favor of include manually the css in the way that the user needs.
> remove injectCss

- example/generateRaws.js
- example/src/demos/raws/vectorLayer.raw
- example/src/demos/sections.tsx
- example/src/demos/vectorLayer.tsx
- package-lock.json
- package.json
- src/geojson-layer.ts
- src/layer.ts
- src/source.ts
In mapbox 1.12.0, [a feature](https://github.com/mapbox/mapbox-gl-js/pull/8048) was released which allows changing the URL/tiles props on a vector source without removing it from the map. This is much more performant, especially in cases where the map undergoes several back-to-back changes to its tiles URL (after a few rapid changes, mapbox-gl starts to have issues when constantly removing/re-adding layers/sources).
In this PR, I've:
- Updated dependency to mapbox-gl to be the latest (I had to make some type changes to get the build to pass, ideally these wouldn't be needed, but I'm hoping these could be resolved at a later date)
- Modified the `Source` component to use the new `setUrl` and `setTiles` APIs when dealing with a vector source. I kept the old behaviour as a fallback, as …
> feat: handle updates to Source tileJsonSource prop more gracefully

- src/geojson-layer.ts
Currently, when the data prop is updated, nothing changes, as the comparison is faulty (it compares in essence `prevProps.data` against itself).
This fixes it, allowing for the `data` prop to change on `GeoJSONLayer` and the underlying source then properly being updated.
> fix: GeoJSONLayer and data prop updating
