README.md, example/all-shapes.js, example/config.json, example/london-cycle.js, example/main.js, src/feature.js, src/layer.js, src/map.js
- Fix Polygon shape on all-shapes example
- Clean all-shapes example
- Add onHover and onEndHover functionality to Feature component
- Pass map object to every events on the map component
=> General improvements

src/map.js
=> Add missing mapbox GL removal for cleaning up

src/popup.js, src/projected-layer.js, src/util/overlays.js
=> Fix Popup className and default anchor props

src/map.js
Added prop to disable/enable drag rotation. Fixes #91
=> Support for drag rotation

src/layer.js, src/source.js
=> dont autoremove source if using sourceId, linting fix

src/map.js
…enter, zoom, and bearing updates.
=> Fix pitch prop not being processed in componentWillReceiveProps

package.json
=> Update mapbox-gl to 0.32.1

docs/API.md
this isnt currently documented and could be discouraging for some who don't peruse the source code :)
=> fitBoundsOptions documentation

docs/API.md, src/__tests__/geojson-layer.test.tsx, src/geojson-layer.ts
layerOptions was missing from GeoJSONLayer, this adds it. I've also added a test.
Tested manually as well, I think this is a very safe change.
=> GeoJSONLayer accepts layerOptions

docs/API.md, src/zoom-control.tsx
It would be more flexible to style if I can pass className to the container. For example I can style the two button as children using className.
=> Add className props

docs/API.md
Did you mean display the marker?
=> Update documentation for Marker

src/layer.ts
=> Watch for `layerOptions.filter` change in props change

example/src/all-shapes.js, example/src/main.js, example/src/style-update.js, src/layer.ts, src/map.tsx
- Remove unnecessary `shouldComponentUpdate` in `map` and `layer` components
- Update all shapes example
- Add switch style example
- Fix https://github.com/alex3165/react-mapbox-gl/issues/129
=> Fix layer style update

package.json, src/cluster.tsx
Fixes rotation/pitch glitch when using clusters.
Also add some tiny deps (turf/bbox and turf/helpers)
=> cluster: use unproject

README.md, docs/API.md, example/package.json, example/src/all-shapes.js, src/index.ts, src/rotation-control.tsx
Should resolve: https://github.com/alex3165/react-mapbox-gl/issues/204
=> Rotation control component

src/cluster.tsx
Reloading features on componentWillReceiveProps
=> Issue #167 - reload features on when children changed

src/__tests__/popup.test.tsx, src/popup.tsx
[Popup] bug with className. Custom className override defaultClassName
=> fix issue #326 [Popup] bug with className

docs/API.md, example/src/demos/londonCycle.tsx, src/__tests__/map.test.tsx, src/map.tsx
@clairethompson Thumb up or down?
=> Add animation and flyTo options

docs/API.md, src/geojson-layer.ts
I needed a way to know when mouse was hovering/clicking on GeoJSONLayer features
=> Added mouse handlers to GeoJSONLayer

docs/API.md, src/__tests__/layer.test.tsx, src/layer.ts
Should solve https://github.com/alex3165/react-mapbox-gl/issues/344
=> Support for adding custom images with Layer component

docs/API.md, src/map.tsx
Should solve https://github.com/alex3165/react-mapbox-gl/issues/396#issuecomment-333327111
=> Add apiUrl parameter to the map factory

example/src/demos/index.tsx, src/__tests__/layer-events-hoc.test.tsx, src/__tests__/layer.test.tsx, src/geojson-layer.ts, src/index.ts, src/layer-events-hoc.tsx, src/layer.ts, src/util/types.ts
Changes:
- Move mouse and touch events from `Layer` component to an HOC
- Add support for dragging on mobile https://github.com/alex3165/react-mapbox-gl/issues/353
- Write some tests for the new HOC
=> Refactor layer events and add support for dragging a feature on mobile

docs/API.md
leaves a note for #413. it would really make it easier for anyone getting started with the map to make this mistake...
=> Leaves a note about centering, to make getting started easier

src/geojson-layer.ts
This resolves #127 for geojson layers also, I hope.
=> Update before in geojson layer

src/popup.tsx, src/projected-layer.tsx
Added support for:
- `onDoubleClick`
- `onScroll`
- `onWheel`
=> Add support for 3 more events to the popup

README.md, docs/API.md
Some stuff was just stylistic, some updates where it wasn't fully clear 👍
=> Proofreading README and API docs

package-lock.json, src/source.ts
the map `load` event is only triggered once and happens before the source is added
=> fix onSourceAdded

package-lock.json, src/__tests__/layer.test.tsx, src/layer.ts
minZoom and maxZoom do not update on changes.
**Warning**: this is not building properly right now, and I get a linting error with tsserver, but I can't figure out what's wrong. I didn't want to create both an issue and a pull request, so I thought we could iterate on this.
The error I get with `npm run build` is
```
src/layer.ts(265,33): error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
Type 'undefined' is not assignable to type 'number'.
```
From what I can tell these are optional params in both `mapbox-gl` and `react-mapbox-gl`, so I'm not sure how to fix the error
```
minZoom?: number;
maxZoom?: number;
```
```
setLayerZoomRange(layerId: string, minzoom: ?number, maxzoom: ?number) {
```
=> update Layer minZoom and maxZoom on changes

example/package-lock.json, package-lock.json, package.json
=> Upgrade to mapbox-gl 0.44

src/rotation-control.tsx
Compass rotation control is the only child in his group, so adding bottom border radiuses.
=> Add border-bottom radiuses to compass rotation control

src/source.ts
This is the same error as #493. The bug was fixed in #500 for when a source is removed, but if a `tileJsonSource` is changed, the source is removed from the map and added again. This modifies the fix from #500 to remove the relevant layers, but then adds them back in after re-adding the source.
=> Fix error updating tileJsonSource in mapbox-gl^0.43

.gitignore, package.json, tsconfig-esm.json, tsconfig.json
Not sure this is the right way to do it, not really familiar with typescript.
Let me know if anything needs to change.
=> Expose esm build

src/__tests__/image.test.tsx, src/image.tsx
=> Fixing error thrown by <Image /> component on unmount

README.md
Use consistent badge styles for better community profiles :)
[![Build Status](https://travis-ci.org/alex3165/react-mapbox-gl.svg?branch=master)](https://travis-ci.org/alex3165/react-mapbox-gl) [![npm version](https://img.shields.io/npm/v/react-mapbox-gl.svg?style=flat)](https://www.npmjs.com/package/react-mapbox-gl) [![npm downloads](https://img.shields.io/npm/dm/react-mapbox-gl.svg)](https://www.npmjs.com/package/react-mapbox-gl) [![TypeScript](https://badges.frapsoft.com/typescript/code/typescript.svg?v=101)](https://github.com/ellerbrock/typescript-badges/)
[![Build Status](https://travis-ci.org/alex3165/react-mapbox-gl.svg?branch=master)](https://travis-ci.org/alex3165/react-mapbox-gl) [![npm version](https://img.shields.io/npm/v/react-mapbox-gl.svg?style=flat)](https://www.npmjs.com/p …
=> Better TypeScript badge

package-lock.json, package.json
Build and tests pass, shouldn't require any other changes?
=> chore: upgrade mapbox-gl to v1.8.1
